#!/usr/bin/env bash

VERSION=1.2
BASH_BINARY="$(which bash)"
TERMV_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/termv"
TERMV_AUTO_UPDATE=${TERMV_AUTO_UPDATE:-true}
TERMV_FULL_SCREEN=${TERMV_FULL_SCREEN:-false}
TERMV_API_URL="https://iptv-org.github.io/iptv/channels.json"
declare -x TERMV_SWALLOW=${TERMV_SWALLOW:-false}
declare -x TERMV_MPV_FLAGS="${TERMV_DEFAULT_MPV_FLAGS:---no-resume-playback}"

mkdir -p "${TERMV_CACHE_DIR:?}"

has() {
    case "$(command -v "$1" 2>/dev/null)" in
        alias*|"") return 1
    esac
}

_phi() {
    >&2 printf '    %s\n' "$1"
}

_pht() {
    >&2 printf '%s\n' "$@"
}

# print error message & exit
_pemx() {
    >&2 printf '\033[31;1merror :\033[m %s\n' "$1"
    exit 1
}

version() {
    _pht "$(basename "$0") $VERSION"
}

usage() {
    _pht "Usage:   $(basename "$0") [OPTIONS] query"
    _pht
    _pht "Options:"
    _pht "  General Options:"
    _phi "-h, --help                Print this help text and exit."
    _phi "-v, --version             Print program version and exit."
    _phi "-u, --update              Update channel list to latest version."
    _pht
    _pht "  Player Options:"
    _phi "-f, --full-screen         Open mpv in fullscreen."
    _phi "-s, --swallow             Swallow terminal during playback (X11 only) based on devour; https://github.com/salman-abedin/devour.sh"
    _pht
    _pht "  Environment variables:  "
    _phi "TERMV_AUTO_UPDATE         Auto update channel list to latest version. (default: true)"
    _phi "TERMV_SWALLOW             Alwayse swallow terminal during playback. (default: false)"
    _phi "TERMV_FULL_SCREEN         Alwayse open mpv in fullscreen. (default: false)"
    _phi "TERMV_DEFAULT_MPV_FLAGS   Default arguments which are passed to mpv. (default: --no-resume-playback)"
    _pht
    _pht "  Improve me on GitHub:"
    _phi "https://github.com/Roshan-R/termv"
}

update_channelsfile() {
    etagPath="${TERMV_CACHE_DIR:?}/etag"
    printf '%s' "Downloading ${TERMV_API_URL:?}... "
    [ -f "${etagPath:?}" ] && oldetag=$(<"${etagPath}") || oldetag="null"

    curl -s "${TERMV_API_URL}" --etag-compare "${etagPath:?}" --etag-save "${etagPath:?}" -o "${TERMV_CACHE_DIR:?}/data.json_new" \
    -H "accept-encoding:gzip" --compressed && downloaded=1 || downloaded=0

    newetag=$(<"${etagPath}")

    if [ ${downloaded} -eq 1 ] && [ "${newetag}" = "${oldetag}" ]; then
        touch "${TERMV_CACHE_DIR:?}/data.json" ;
        printf '\033[33;1m %s \033[0m\n' "Your version is already up to date." ;
    elif [ ${downloaded} -eq 1 ]; then
        mv -f "${TERMV_CACHE_DIR:?}/data.json_new" "${TERMV_CACHE_DIR:?}/data.json"
        printf '\033[32;1m %s \033[0m\n' "Done!" ;
    elif [ ${downloaded} -eq 0 ]; then
        rm -f "${etagPath:?}" "${TERMV_CACHE_DIR:?}/data.json_new"
        echo "${oldetag}" > "${etagPath}"
        printf '\033[31;1m %s \033[0m\n' "Uh oh, failed!"
        exit 1
    fi
}

# check if necessary programs are installed
for prog in mpv fzf jq curl gawk; do
     ! has "$prog" && dependencies_not_installed="${dependencies_not_installed}${prog}, "
done

[ -n "${dependencies_not_installed}" ] && _pemx "Missing dependencies, please install: ${dependencies_not_installed%??}."

while [ "$1" ]; do
    case "$1" in
        "-h"|"--help")
            usage ; exit 0 ;;
        "-v"|"--version")
            version ; exit 0 ;;
        "-u"|"--update")
            update_channelsfile ; exit ;;

        "-f"|"--full-screen")
            TERMV_FULL_SCREEN=true   ; shift ;;
        "-s"|"--swallow")
            TERMV_SWALLOW=true       ; shift ;;

        "--")
            shift ; break ;;
        -*)
            _pemx "$1 in not a supported option" ;;
        *)
            break ;;
    esac
done

[ "${TERMV_SWALLOW}" = true ] && { ! has "xdo" && _pemx "Dependency missing for '-s' flag, please install xdo."; }

[ "${TERMV_FULL_SCREEN}" = true ] && TERMV_MPV_FLAGS="${TERMV_MPV_FLAGS} --fs"

[ "${TERMV_AUTO_UPDATE}" = true ] && { [ ! "$(stat -c %y "${TERMV_CACHE_DIR:?}/data.json" 2>/dev/null | cut -d' ' -f1)" = "$(date '+%Y-%m-%d')" ] && update_channelsfile ; }

CHANNELS_LIST=$(jq -r '.[] | "\(.name) \t \(.category // "n/a") \t \(.languages|.[0].name // "n/a") \t \(.countries|.[0].name // "n/a") \t \(.url)"' "${TERMV_CACHE_DIR:?}/data.json" |\
                gawk -v max="${COLUMNS:-80}" 'BEGIN { RS="\n"; FS=" \t " }
                    {
                      name = substr(gensub(/[0-9]+\.\s*(.*)/, "\\1", "g", $1),0,max/4)
                      category = substr(gensub(/\s+> (.*)/, "\\1", "g", $2),0,max/8)
                      languages = substr(gensub(/\s+> (.*)/, "\\1", "g", $3),0,max/8)
                      countries = substr(gensub(/\s+> (.*)/, "\\1", "g", $4),0,70)
                      channelUrl = substr(gensub(/\s+> (.*)/, "\\1", "g", $5),0)
                      print name "\t|" category "\t|" languages "\t|" countries "\t" channelUrl
                    }' | column -t -s $'\t' \
                )

_play() {
    printf '%s\n' "Fetching channel, please wait..."
    if [ "${TERMV_SWALLOW}" = true ]; then
        WID=$(xdo id)
        xdo hide
        # shellcheck disable=SC2086
        mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}" --force-window=immediate
        xdo show "$WID" && xdo activate "$WID"
    else
        # shellcheck disable=SC2086
        mpv "${*##* }" ${TERMV_MPV_FLAGS} --force-media-title="${*%%  *}"
    fi
}

export -f _play

SHELL="${BASH_BINARY}" \
            fzf -e -i --reverse --cycle --with-nth="1..-2"\
            --bind "enter:execute(_play {})"\
            --bind "double-click:execute(_play {})"\
            --header="Select channel (press Escape to exit)" -q "${*:-}" \
            < <( printf '%s\n' "${CHANNELS_LIST}" )
